parameters:
- name: Artifacts
  type: object
  default:
    - name: Azure.MixedReality.Authentication
      safeName: AzureMixedRealityAuthentication
- name: ArtifactStages
  type: stagelist
  values:
    - name: Azure.MixedReality.Authentication
      safeName: AzureMixedRealityAuthentication
    - name: Azure.MixedReality.Authentication2
      safeName: AzureMixedRealityAuthentication2
- name: myString
  type: string
  default: a string
- name: myMultiString
  type: string
  default: default
  values:
  - default
  - ubuntu
- name: myNumber
  type: number
  default: 2
  values:
  - 1
  - 2
  - 4
  - 8
  - 16
- name: myBoolean
  type: boolean
  default: true
- name: myObject
  type: object
  default:
    foo: FOO
    bar: BAR
    things:
    - one
    - two
    - three
    nested:
      one: apple
      two: pear
      count: 3
- name: myStep
  type: step
  default:
    script: echo my step
- name: mySteplist
  type: stepList
  default:
    - script: echo step one
    - script: echo step two

# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  branches:
    include:
    - main
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/mixedreality/

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/mixedreality/

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: mixedreality
    ArtifactName: packages
    Artifacts: ${{ parameters.Artifacts }}

